apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - args:
            - make
            - prepare-env
          env:
            - name: DATABASE_HOST
              value: 
            - name: DATABASE_PASS
              value: toor
            - name: DATABASE_USER
              value: root
            - name: GIN_MODE
              value: release
          image: leozz37/go-k8s-gcp-terraform:latest
          name: api
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
